### ISSUE TITLE
VPX provisioning returns an error after finish

### ISSUE THREAD

**Issue by 54321ivan** [citrix/terraform-provider-citrixsdx#11]
Hello Team,

I'm currently testing provisioning a VPX instance on our SDX 14000 platform. The VPX instance has been provisioned on the SDX with the correct parameters but the Terraform returned an error in the end and crashed:

citrixsdx_provision_vpx.net-instanceTEST: Still creating... [2m10s elapsed]
citrixsdx_provision_vpx.net-instanceTEST: Still creating... [2m20s elapsed]
citrixsdx_provision_vpx.net-instanceTEST: Still creating... [2m30s elapsed]
╷
│ Error: Plugin did not respond
│ 
│   with citrixsdx_provision_vpx.net-instanceTEST,
│   on resource.tf line 1, in resource "citrixsdx_provision_vpx" "net-instanceTEST":
│    1: resource "citrixsdx_provision_vpx" "net-instanceTEST" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
│ more details.
╵

Stack trace from the terraform-provider-citrixsdx_v0.1.0 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 9 [running]:
terraform-provider-citrixsdx/citrixsdx.resourceProvisionVpxRead({0xc00028d100?, 0xc00021e1e0?}, 0xc00028d100, {0xba59c0?, 0xc00021a960})
        terraform-provider-citrixsdx/citrixsdx/resource_citrixsdx_provision_vpx.go:2046 +0x47c5
terraform-provider-citrixsdx/citrixsdx.resourceProvisionVpxCreate({0xd1b128, 0xc0000837a0}, 0xb2ad60?, {0xba59c0?, 0xc00021a960?})
        terraform-provider-citrixsdx/citrixsdx/resource_citrixsdx_provision_vpx.go:1980 +0x370
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0004562a0, {0xd1b160, 0xc0004ef500}, 0xd?, {0xba59c0, 0xc00021a960})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0004562a0, {0xd1b160, 0xc0004ef500}, 0xc000250dd0, 0xc000543600, {0xba59c0, 0xc00021a960})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00028b1b8, {0xd1b160?, 0xc0004ef440?}, 0xc0005809b0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0002ea320, {0xd1b160?, 0xc0004eecf0?}, 0xc0004de4d0)
        github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/tf5server/server.go:813 +0x4fc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xbcf920?, 0xc0002ea320}, {0xd1b160, 0xc0004eecf0}, 0xc000082fc0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002a8700, {0xd1db90, 0xc000476ea0}, 0xc00052bb00, 0xc0004745d0, 0x11805e0, 0x0)
        google.golang.org/grpc@v1.47.0/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc0002a8700, {0xd1db90, 0xc000476ea0}, 0xc00052bb00, 0x0)
        google.golang.org/grpc@v1.47.0/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.47.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.47.0/server.go:920 +0x28a

Error: The terraform-provider-citrixsdx_v0.1.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by rohit-myali** [comment]
Hey @54321ivan, 
We have migrate out provider to latest terraform-plugin-framework, would you try now to provision VPX?
Please update us here on the same!


Thanks
Rohit
